version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_backend
    restart: always
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=backend.settings
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=novell
      - CELERY_BROKER_URL=redis://default:novell@redis:6379/0
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - celery

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_celery
    restart: always
    command: poetry run celery -A backend worker --loglevel=info
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - redis
    environment:
      - broker_connection_retry_on_startup=True
      - CELERY_BROKER_URL=redis://default:novell@redis:6379/0

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_flower
    restart: always
    command: poetry run celery -A backend --broker=redis://default:novell@redis:6379  flower --port=5555
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - celery
      - redis
    ports:
      - "5555:5555"

  redis:
    image: redis:alpine
    container_name: django_redis
    ports:
      - "6379:6379"
    restart: always
    environment:
      REDIS_HOST_PASSWORD: 'novell'
    command: /bin/sh -c "redis-server --requirepass $$REDIS_HOST_PASSWORD"
    volumes:
      - .:/data
